<?php
	session_register('logged_in');
	session_register('allow_admin');
	session_register('allow_edit');
	session_register('allow_add');
	session_register('tentative_edit');
	session_register('allow_delete');
	session_register('allow_media_edit');
	session_register('allow_media_add');
	session_register('allow_media_delete');
	session_register('allow_living');
	session_register('allow_private');
	session_register('allow_ged');
	session_register('allow_pdf');
	session_register('allow_lds');
	session_register('mygedcom');
	session_register('mypersonID');
	session_register('assignedtree');
	session_register('assignedbranch');
	session_register('currentuser');
	session_register('currentuserdesc');
	session_register('session_rp');
    session_register('lastcite');
?>
